name: Build e Deploy .NET

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o /var/www/deploy-lab

      - name: Copiar para pasta de destino
        run: sudo cp -r ./publish/* /var/www/deploy-lab/

      - name: Reiniciar Serviço da API
        run: sudo systemctl restart deploy-lab.service
